[tool.black]
line-length = 140
target-version = ['py311']

[tool.isort]
profile = "django"
line_length = 140

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "PROJ3CT.settings"
python_files = "test_*.py"
minversion = "7.4.0"
pythonpath = "./PROJ3CT/**/test_*.py"
addopts = """
    -ra -q -s -x -vvv \
    --doctest-modules \
    --disable-pytest-warnings \
    --cov=PROJ3CT \
    --cov-report=html:coverage
    """

[tool.coverage.report]
skip_empty = true
branch = true
source = "PROJ3CT/**/*.py"
omit = [
    "PROJ3CT/**/migrations/*.py",
    "PROJ3CT/*.py",
    "PROJ3CT/**/populate_recipes.py",
    "PROJ3CT/**/factory.py"
]

[tool.taskipy.tasks]
lint = 'make lint'
format = 'make format'
run = 'make run'
migrate = 'make migrate'
migrations = 'make migrations'
shell = 'make shell'
pre_test = 'make lint'
test = 'make test'
