# Generated by Django 5.0 on 2024-01-09 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20, unique=True)),
                ("nome_interno", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=40)),
                ("nome_interno", models.CharField(max_length=40)),
                ("idade", models.PositiveIntegerField()),
                ("time", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="futebol.time")),
            ],
        ),
    ]
