# Generated by Django 5.0 on 2024-01-07 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Time",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Jogador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("idade", models.PositiveIntegerField()),
                ("time", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="futebol.time")),
            ],
        ),
    ]
