# Generated by Django 5.0 on 2024-01-14 20:10

import django.utils.timezone
from django.db import migrations, models

import PROJ3CT.core.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("email", models.EmailField(default="", max_length=254, unique=True, verbose_name="Email")),
                ("name", models.CharField(blank=True, default="", max_length=255, verbose_name="Name")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("is_staff", models.BooleanField(default=False, verbose_name="Staff")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="Superuser")),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date Joined")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="Last Login")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", PROJ3CT.core.models.CustomUserManager()),
            ],
        ),
    ]
